### PR TITLE
Support long file names on Windows

### PR DESCRIPTION
**Pull request by softworkz**
This patchset adds support for long file and directory paths on Windows.
The implementation follows the same logic that .NET is using internally,
with the only exception that it doesn't expand short path components
in 8.3 format. .NET does this as the same function is also used for other 
purposes, but in our case, that's not required. Short (8.3) paths are working
as well with the extended path prefix, even when longer than 260.

Successfully tested:

- Regular paths wth drive letter
- Regular UNC paths
- Long paths wth drive letter
- Long paths wth drive letter and forward slashes
- Long UNC paths
- Prefixed paths wth drive letter
- Prefixed UNC paths

I have kept the individual functions separate on purpose, to make it
easy to compare with the .NET impl. 
(compilers should inlinie those anyway)

v2    
- wchar_filename: Improve comments and function documentation    
- os_support: adjust defines to use win32_stat    

v3    
- removed length check in path_is_extended()    
- added path_is_device_path() check in add_extended_prefix()    
- add_extended_prefix(): clarified doc and add checks    
- clarified string allocation length calculation    
- replaced 260 with MAX_PATH    
- removed redundant checks after normalization    

v4
- rebased. no changes    

v5
- resolved the ugly struct duplication    
- compatible with _USE_32BIT_TIME_T    

v6
- wchar_filename.h: added links to .NET source code    
- wchar_filename.h: free allocations on error    
- os_support.hs: use clean and safe way to redirect stat() calls    

v7
- os_support.h: remapped fstat with win32_stat structure    
- os_support.h: use int64_t for some members    
- avformat/file: remove _WIN32 condition    

v8
- os_support.h: documented win32_stat structure    
- os_support.h: renamed function parameters    

cc: Soft Works <softworkz@hotmail.com>
cc: Hendrik Leppkes <h.leppkes@gmail.com>
cc: Martin Storsjö <martin@martin.st>

### CODE REVIEW

**Comment by softworkz** [comment]
Merged into master

**Comment by nanake** [comment]
@softworkz this causes build failed on win32 https://0x0.st/oMIX.log

**Comment by nanake** [comment]
> @nanake - yes, when USE_32BIT_TIME_T is specifified. To fix, you also need to apply this: #35

thanks, build passed locally.
waiting for #35 to get merged.

**Pull request closed without merging**
