### PR TITLE
avformat/movenc: fix tfra box

### PR DESCRIPTION
**Pull request by quink-black**

### CODE REVIEW

**Comment by softworkz** [comment]
> Error: User softworkz lacks permission for this.

That's funny - I'll fix this

**Comment by softworkz** [comment]
@quink-black - you can now post a comment with "/submit" to have the patch e-mails generated and sent to you

**Comment by quink-black** [comment]
> @quink-black - you can now post a comment with "/submit" to have the patch e-mails generated and sent to you

The patchset has already been sent to the mailing list before, I'm trying to test how this works. 😃

**Comment by softworkz** [comment]
You can post **/submit** safely. The e-mails are only sent to your own account - sending to the ML is not activated yet.

You can also post **/preview** which will always send the e-mails to yourself only, but not the ML (even later, when it's activated).

**Comment by softworkz** [comment]
Here's a rough overview about how it's working:

- User submits a PR to the GitHub repo

- When it's a user's first PR, the ffmpeg-codebot will 
  respond with a very comprehensive message (as PR comment),
  explaining the procedures and providing an overview about
  contributing to ffmpeg with links to the individual topics 
  on the ffmpeg website regarding contributing.

- The message further explains that first-time users are not
  allowed to submit immediately, and that a user needs to
  find and contact another developer who is allowed to make
  submissions and ask that developer to vouch for him.

- Every developer who has been allowed to submit can vouch
  for a first-time submitter
  It is done by adding a comment containing "/allow" to the
  first-time user's PR

- Upon submitting the PR (no matter whether first-time or existing
  submitter), the code bot will likely have posted some other 
  comments, indicating which changes need to be made to the  
  patchset before it can be submitted.

- The user addresses those changes and then force-pushes the branch
  to GitHub, the code bot re-runs all checks and when all 
  requirements are met (and only then), the user will be 
  able to submit.
  This is done by posting a comment to the PR containing "/submit"
  The code bot will automatically create the patch e-mails and 
  send them to the ML.
  (it's also possible to post "/preview" to get the same e-mails
  created but only sent to a user's own e-mail account)

- Comments that are made on the ML are mirrored back to the GitHub
  PR as comments. The other way is not yet implemented, so at this
  point, a user will need to respond through the ML (that's 
  clearly indicated).
  I hope this will be implemented soon, it's not easy though to
  do it in a nice way without repeating all those quoted lines 
  each time

Submitting new versions of a patchset:

- After having applied the changes locally, you just (force-) push
  the branch again, and post another comment with "/submit"
  Everything is done automatically then: the patchset version 
  number is increased, new patches are generated and sent to the ML

**Pull request closed without merging**
